### ISSUE TITLE
Source for brew-cask-fonts

### ISSUE THREAD

**Issue by dustinknopoff** [anewtypeofinterference/Optician-Sans#1]
I've added optician-sans to [brew-cask-fonts](
https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-optician-sans.rb). At the time I added it, there was only the option to download from the website. Is it better to have it be downloaded from this repo?

**Comment by scannerlicker** [comment]
Well, yes, although we haven't announced it. We're still organizing the repo.

**Comment by schikulski** [comment]
Yes, definitely link to this repo instead. I'll change the link on the website so it points to the master branch on this repo too. That way we'll have one place to store the latest version as well as the file history.

**Comment by dustinknopoff** [comment]
@schikulski Please see the reason for the pull request being closed.

**Comment by schikulski** [comment]
Ok, fixed. There's a direct link to this repo from the website now.
