### ISSUE TITLE
Tumbling Es

### ISSUE THREAD

**Issue by gtwy** [anewtypeofinterference/Optician-Sans#5]
Most optotypes support flipped and rotated letter Es. These are called "Tumbling Es"

If you wanted to add this feature, the first and easiest would be this reversed glyph: Ǝ (U+018E)

The second two would be a little bit harder, one rotated 90 degrees clockwise and the other 90 degrees counter clockwise. It could be done in the Private Use Areas of Unicode. Because horizontal writing isn't going to work, the glyph will still write left to write horizontally, but will appear to be rotated at 90 degrees. This is actually fine for our purposes.

![Medical_Instrument_Eye_Visual_acuity_chart_E_chart](https://user-images.githubusercontent.com/11441407/58515729-bafee580-8173-11e9-906b-9103f9deb3a3.jpg)

**Comment by scannerlicker** [comment]
Optician Sans doesn't feature optotypes: it is not designed to measure visual acuity.

**Comment by gtwy** [comment]
Thanks for the response.
